### PR TITLE
Disable deep watcher on $props

### LINKED ISSUE #27: [Vue warn]: Error in nextTick: "RangeError: Maximum call stack size exceeded"
e.g.
https://codesandbox.io/embed/vue-template-3wd0w

The key point is on the container property
Is my usage wrong?

### PR DESCRIPTION
**Pull request by romansp**
Fixes #27.

This PR tries to mitigate issue by dropping `deep: true` from watcher and provides another way to handle props updates to be passed correctly to `Moveable` instance.

### CODE REVIEW

**Comment by romansp** [comment]
@probil This is somewhat work in progress. Not sure what scope of changes you expect in this PR. I really like you approach to deep-watching described here: https://github.com/probil/vue-moveable/issues/27#issuecomment-543252419

I guess it also implies that component `props` themselves will be constructed dynamically? Maybe drop `$props` altogether and switch to `$attrs`?

Few tests will also be a cool addition to that.

Should I implement it in this PR, or open another one?

**Comment by probil** [comment]
Hi @romansp

The scope of this PR is to fix `Maximum call stack size exceeded` and keep existing functionality in place.

I think you can simplify it a bit for now.
```js
const watchReactiveProp = key => function (newValue) {
  const existingValue = this.moveable[key]; 
  if (existingValue === newValue) return; 
  this.moveable[key] = newValue; 
}

export default {
  // ...
  watch: {
      draggable: watchReactiveProp('draggable'),
      resizable: watchReactiveProp('resizable'),
      scalable: watchReactiveProp('scalable'),
      rotatable: watchReactiveProp('rotatable'),
      warpable: watchReactiveProp('warpable'),
      pinchable: watchReactiveProp('pinchable'),
      origin: watchReactiveProp('origin'),
      throttleDrag: watchReactiveProp('throttleDrag'),
      throttleResize: watchReactiveProp('throttleResize'),
      throttleScale: watchReactiveProp('throttleScale'),
      throttleRotate: watchReactiveProp('throttleRotate'),
      keepRatio: watchReactiveProp('keepRatio'),
  }
}
```
I'll merge and then we can figure out how to make it more maintainable

**Comment by romansp** [comment]
Okay, I updated PR. Changed to something that's closer to https://github.com/probil/vue-moveable/issues/27#issuecomment-543252419.

**Comment by probil** [comment]
Remove `[WIP]` prefix when it's ready for review & merge

File: src/components/Moveable.vue [hunk 1]
```diff
@@ -28,6 +28,35 @@ const ALLOWED_EVENTS = [
...
+  handler(newValue) {
+    const existingValue = this.moveable[key];
+    if (existingValue === newValue) return;
+    this.moveable[key] = newValue;
+  },
+  deep,
+});
+
+const watchMoveableProps = () => MOVEABLE_PROPS.reduce((acc, prop) => {
+  acc[prop] = watchReactiveProp(prop, true);
```
Comment (probil) [inline src/components/Moveable.vue]: I don't think we need `deep` here 🤔 
But let it be.

Comment (romansp) [reply src/components/Moveable.vue]: Absolutely agree, I decided to implement it in this way to accommodate for future upgrade to newer versions of `Movable`, so we don't have to think about changes in underlying API.
